# Rebuilds the single-file function copies in this folder (for the dashboard editor). Run from the repo root.
import re
for name in ('strava', 'techpay', 'notify'):
    util = open('supabase/functions/_shared/util.ts').read()
    strava = open('supabase/functions/_shared/strava.ts').read()
    main = open(f'supabase/functions/{name}/index.ts').read()
    strip = lambda s: re.sub(r"^import [^;]*from '(\./util|\.\./_shared/[^']+)(\.ts)?';\n", "", s, flags=re.M)
    parts = [f"// Single-file copy of supabase/functions/{name} for pasting into the Supabase dashboard.\n// Generated by supabase/paste/build.py; edit the originals, not this file.\n", util]
    if name in ('strava', 'notify'): parts.append(strip(strava))
    parts.append(strip(main))
    out = "\n".join(parts)
    imports = sorted(set(re.findall(r"^import .* from 'npm:[^']+';$", out, flags=re.M)))
    out = re.sub(r"^import .* from 'npm:[^']+';\n", "", out, flags=re.M)
    open(f'supabase/paste/{name}.ts', 'w').write("\n".join(imports) + "\n" + out)
