import { createClient, SupabaseClient } from 'npm:@supabase/supabase-js@2';
// Single-file copy of supabase/functions/notify for pasting into the Supabase dashboard.
// Generated by supabase/paste/build.py; edit the originals, not this file.


export const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
};

export const json = (b: unknown, status = 200) =>
  new Response(JSON.stringify(b), { status, headers: { ...CORS, 'Content-Type': 'application/json' } });

export const env = (k: string, d = '') => Deno.env.get(k) ?? d;

export const admin = (): SupabaseClient =>
  createClient(env('SUPABASE_URL'), env('SUPABASE_SERVICE_ROLE_KEY'), { auth: { persistSession: false } });

/** Client acting as the caller (their JWT), so RLS and auth.uid() apply. */
export const asUser = (req: Request): SupabaseClient =>
  createClient(env('SUPABASE_URL'), env('SUPABASE_ANON_KEY'), {
    global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } },
    auth: { persistSession: false },
  });

export async function currentUser(req: Request) {
  const { data } = await asUser(req).auth.getUser();
  return data.user ?? null;
}

export async function appUrl(): Promise<string> {
  const fromEnv = env('APP_URL');
  if (fromEnv) return fromEnv.replace(/\/$/, '');
  try {
    const { data } = await admin().from('app_config').select('value').eq('key', 'app_url').single();
    return String(data?.value ?? '').replace(/\/$/, '');
  } catch { return ''; }
}

export async function hmacHex(key: string, msg: string): Promise<string> {
  const k = await crypto.subtle.importKey('raw', new TextEncoder().encode(key), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const mac = await crypto.subtle.sign('HMAC', k, new TextEncoder().encode(msg));
  return Array.from(new Uint8Array(mac)).map((b) => b.toString(16).padStart(2, '0')).join('');
}

/** Constant-time string compare */
export function same(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let r = 0;
  for (let i = 0; i < a.length; i++) r |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return r === 0;
}

export const peso = (n: number) => '₱' + Math.round(n).toLocaleString('en-PH');
export const manilaTime = (iso: string) =>
  new Date(iso).toLocaleTimeString('en-PH', { hour: 'numeric', minute: '2-digit', timeZone: 'Asia/Manila' });


const API = 'https://www.strava.com/api/v3';

export type StravaAccount = {
  user_id: string; athlete_id: number; access_token: string; refresh_token: string; expires_at: string; write_ok: boolean;
};

/** Returns a valid access token, refreshing and saving it when it is about to expire. */
export async function accessToken(acc: StravaAccount): Promise<string> {
  if (new Date(acc.expires_at).getTime() - Date.now() > 120_000) return acc.access_token;
  const r = await fetch('https://www.strava.com/oauth/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      client_id: env('STRAVA_CLIENT_ID'), client_secret: env('STRAVA_CLIENT_SECRET'),
      grant_type: 'refresh_token', refresh_token: acc.refresh_token,
    }),
  });
  const j = await r.json();
  if (!j.access_token) throw new Error('Strava refresh failed: ' + (j.message ?? r.status));
  await admin().from('strava_accounts').update({
    access_token: j.access_token, refresh_token: j.refresh_token,
    expires_at: new Date(j.expires_at * 1000).toISOString(),
  }).eq('user_id', acc.user_id);
  acc.access_token = j.access_token; acc.refresh_token = j.refresh_token; acc.expires_at = new Date(j.expires_at * 1000).toISOString();
  return j.access_token;
}

export async function stravaGet(acc: StravaAccount, path: string) {
  const t = await accessToken(acc);
  const r = await fetch(API + path, { headers: { Authorization: `Bearer ${t}` } });
  if (r.status === 404) return null;
  if (!r.ok) throw new Error(`Strava ${path} → ${r.status}`);
  return r.json();
}

export async function stravaPut(acc: StravaAccount, path: string, body: unknown) {
  const t = await accessToken(acc);
  const r = await fetch(API + path, {
    method: 'PUT', headers: { Authorization: `Bearer ${t}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body),
  });
  if (!r.ok) throw new Error(`Strava PUT ${path} → ${r.status}`);
  return r.json();
}

export const OUTDOOR = /ride|cycl|bike|gravel|mountain|handcycle|velomobile/i;

/** Pull one activity's route and record the moments it passed a pitikero. Keeps only a thinned track, briefly. */
export async function processActivity(acc: StravaAccount, activityId: number, summary?: Record<string, any>) {
  const a = summary ?? await stravaGet(acc, `/activities/${activityId}`);
  if (!a) return { skipped: 'not found' };
  const type = String(a.sport_type ?? a.type ?? '');
  if (a.trainer || /virtual/i.test(type) || !OUTDOOR.test(type)) return { skipped: 'not an outdoor ride' };
  const streams = await stravaGet(acc, `/activities/${activityId}/streams?keys=latlng,time&key_by_type=true`);
  const ll: [number, number][] = streams?.latlng?.data ?? [];
  const tt: number[] = streams?.time?.data ?? [];
  if (!ll.length || ll.length !== tt.length) return { skipped: 'no GPS' };
  const start = Date.parse(a.start_date);
  const track = ll.map(([lat, lon], i) => ({ t: new Date(start + tt[i] * 1000).toISOString(), lat, lon }));
  const end = new Date(start + (tt[tt.length - 1] ?? 0) * 1000).toISOString();
  const { data, error } = await admin().rpc('ingest_ride', {
    p_user: acc.user_id, p_source: 'strava', p_activity: activityId, p_name: a.name ?? 'Ride',
    p_start: new Date(start).toISOString(), p_end: end, p_track: track,
  });
  if (error) throw new Error(error.message);
  return data;
}

export const LINE_MARK = '📸 Pitik:';

/** Add or replace our one line in the activity description, leaving the rider's own text alone. */
export function mergeDescription(current: string | null | undefined, line: string): string {
  const lines = String(current ?? '').split('\n').filter((l) => !l.trim().startsWith(LINE_MARK));
  while (lines.length && !lines[lines.length - 1].trim()) lines.pop();
  return (lines.length ? lines.join('\n') + '\n\n' : '') + line;
}

// notify — runs every 15 minutes (pg_cron). For each ride that is ready, sends ONE message:
//   • a line in the Strava activity description (edited, never duplicated)
//   • one email listing every pitikero who caught the rider
// At most one follow-up per ride if more shots land later. No SMS.
// Called with header x-cron-secret (from Vault). Secrets: RESEND_API_KEY, EMAIL_FROM, APP_URL.

type Pass = { pitikero: string; passed_at: string; count: number; thumb: string | null };
type Ride = {
  ride_id: string; user_id: string; email: string | null; email_notify: boolean; strava_activity_id: number | null;
  name: string | null; started_at: string; is_followup: boolean; passes: Pass[];
};

const esc = (s: string) => s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]!));
const joinNames = (n: string[]) => n.length <= 1 ? (n[0] ?? '') : n.slice(0, -1).join(', ') + ' & ' + n[n.length - 1];

function summary(r: Ride) {
  const withShots = r.passes.filter((p) => p.count > 0);
  const names = [...new Set(withShots.map((p) => p.pitikero))];
  const total = withShots.reduce((a, p) => a + p.count, 0);
  return { withShots, names, total };
}

async function sendEmail(to: string, subject: string, html: string) {
  if (!env('RESEND_API_KEY')) return 'skipped: no RESEND_API_KEY';
  const r = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: { Authorization: `Bearer ${env('RESEND_API_KEY')}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ from: env('EMAIL_FROM', 'Pitik <hello@pitik.ph>'), to: [to], subject, html }),
  });
  return r.ok ? 'sent' : `failed ${r.status}`;
}

function emailHtml(r: Ride, link: string) {
  const { withShots, names, total } = summary(r);
  const pub = `${env('SUPABASE_URL')}/storage/v1/object/public/previews/`;
  const rows = withShots.map((p) => `
    <tr><td style="padding:10px 0;border-top:1px solid #E2DACB">
      ${p.thumb ? `<img src="${pub}${esc(p.thumb)}" width="96" height="72" style="border-radius:8px;object-fit:cover;vertical-align:middle;margin-right:12px" alt="">` : ''}
      <span style="font:600 16px Georgia,serif">${esc(p.pitikero)}</span>
      <span style="color:#4A443B"> caught you at ${manilaTime(p.passed_at)} · ${p.count} photo${p.count > 1 ? 's' : ''}</span>
    </td></tr>`).join('');
  return `<!doctype html><html><body style="margin:0;background:#F4EFE6;font-family:Helvetica,Arial,sans-serif;color:#1F1B16">
  <table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 16px">
  <table width="100%" style="max-width:520px;background:#FBF8F2;border-radius:18px;padding:24px" cellpadding="0" cellspacing="0">
    <tr><td style="font:italic 600 28px Georgia,serif">pitik</td></tr>
    <tr><td style="font:500 24px Georgia,serif;padding-top:12px">${r.is_followup ? 'May bagong pitik ka.' : 'Nakuhanan ka kaninang umaga.'}</td></tr>
    <tr><td style="color:#4A443B;padding:6px 0 10px">${total} photo${total > 1 ? 's' : ''} of you from ${esc(joinNames(names))}${r.name ? ` on “${esc(r.name)}”` : ''}. Only you can see them.</td></tr>
    ${rows}
    <tr><td style="padding-top:18px"><a href="${link}" style="display:inline-block;background:#B8441F;color:#fff;text-decoration:none;font-weight:600;padding:14px 22px;border-radius:14px">Tingnan lahat</a></td></tr>
    <tr><td style="color:#6E655A;font-size:12px;padding-top:18px">The pitikero keeps 100% of the photo price and every tip. You got this because your Strava is connected to Pitik. Turn emails off anytime in your Pitik settings.</td></tr>
  </table></td></tr></table></body></html>`;
}

Deno.serve(async (req) => {
  const secret = req.headers.get('x-cron-secret') ?? '';
  const { data: okSecret } = await admin().rpc('check_cron_secret', { p: secret });
  if (!okSecret) return json({ error: 'forbidden' }, 403);

  const app = await appUrl();
  const { data, error } = await admin().rpc('rides_to_notify');
  if (error) return json({ error: error.message }, 500);
  const rides = (data ?? []) as Ride[];
  const results: unknown[] = [];

  for (const r of rides) {
    const { names, total } = summary(r);
    if (!total) continue;
    const link = `${app}/ride/${r.ride_id}`;
    const line = `${LINE_MARK} ${total} photo${total > 1 ? 's' : ''} of you from ${joinNames(names)} → ${link}`;
    const out: Record<string, unknown> = { ride: r.ride_id };

    if (r.strava_activity_id) {
      try {
        const { data: acc } = await admin().from('strava_accounts').select('*').eq('user_id', r.user_id).maybeSingle();
        if (acc && (acc as StravaAccount).write_ok) {
          const a = await stravaGet(acc as StravaAccount, `/activities/${r.strava_activity_id}`);
          if (a) {
            await stravaPut(acc as StravaAccount, `/activities/${r.strava_activity_id}`, { description: mergeDescription(a.description, line) });
            out.strava = 'updated';
          }
        } else out.strava = 'no write permission';
      } catch (e) { out.strava = 'failed: ' + (e as Error).message; }
    }

    if (r.email && r.email_notify) {
      const subject = r.is_followup
        ? 'May bagong pitik ka 📸'
        : `Nakita ka ng ${names.length} pitikero${names.length > 1 ? 's' : ''} kaninang umaga 📸`;
      try { out.email = await sendEmail(r.email, subject, emailHtml(r, link)); }
      catch (e) { out.email = 'failed: ' + (e as Error).message; }
    }

    // If every channel we tried failed, try again on the next run (gives up after 4 tries)
    const tried = [out.strava, out.email].filter((v) => v !== undefined && v !== 'no write permission' && !String(v).startsWith('skipped'));
    const anyOk = !tried.length || tried.some((v) => v === 'updated' || v === 'sent');
    await admin().rpc('mark_notified', { p_ride: r.ride_id, p_line: line, p_ok: anyOk });
    results.push(out);
  }
  return json({ ok: true, count: results.length, results });
});
